/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.ads.poo.biblioteca.Interface;

import br.edu.ifpb.ads.poo.biblioteca.Controllers.UsuarioLoginControl;
import br.edu.ifpb.ads.poo.biblioteca.Dao.BibliotecaDAO;
import br.edu.ifpb.ads.poo.biblioteca.Entidades.Aluno;
import br.edu.ifpb.ads.poo.biblioteca.Entidades.Emprestimo;
import br.edu.ifpb.ads.poo.biblioteca.Entidades.Exemplares;
import br.edu.ifpb.ads.poo.biblioteca.Entidades.Funcionario;
import br.edu.ifpb.ads.poo.biblioteca.Entidades.Usuario;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 * @version 1.0
 * @author Wensttay de Sousa Alencar <yattsnew@gmail.com>
 * @date 07/01/2017 - 12:01:31
 */
public class UsuarioLoginFrame extends javax.swing.JFrame {

    UsuarioLoginControl usuarioLoginControl;
    BibliotecaDAO bibliotecaDAO;
    Exemplares exemplares;
    JList lista_de_Livros;
    List<Exemplares> livros;

    /**
     * Creates new form UsuarioLoginFrame
     */
    /**
     *
     * @throws IOException error de arquivos
     */
    public UsuarioLoginFrame() throws IOException {
        initComponents();
    }

    public UsuarioLoginFrame(Exemplares exemplar, Exemplares exemplares, JList lista_De_Livros, List<Exemplares> livros) throws IOException {
        initComponents();
        this.bibliotecaDAO = new BibliotecaDAO(false);
        this.usuarioLoginControl = new UsuarioLoginControl();
        this.exemplares = exemplar;
        this.lista_de_Livros = lista_De_Livros;
        this.livros = livros;
        this.exemplares = exemplares;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginjLabel = new javax.swing.JLabel();
        senhajPassword = new javax.swing.JPasswordField();
        senhajLabel = new javax.swing.JLabel();
        enviarjButton = new javax.swing.JButton();
        matriculajFormattedTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuario Login");
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        loginjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginjLabel.setText("Matrícula");

        senhajPassword.setToolTipText("Digite sua Senha");
        senhajPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senhajPasswordapagarSenha(evt);
            }
        });
        senhajPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhajPasswordActionPerformed(evt);
            }
        });
        senhajPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhajPasswordapagarSenha2(evt);
            }
        });

        senhajLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        senhajLabel.setText("Senha");

        enviarjButton.setText("Enviar");
        enviarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarjButtonActionPerformed(evt);
            }
        });

        try {
            matriculajFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enviarjButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhajPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(matriculajFormattedTextField))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginjLabel)
                    .addComponent(matriculajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhajPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhajLabel))
                .addGap(18, 18, 18)
                .addComponent(enviarjButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void senhajPasswordapagarSenha(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senhajPasswordapagarSenha
        this.senhajPassword.setText("");
    }//GEN-LAST:event_senhajPasswordapagarSenha

    private void senhajPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhajPasswordActionPerformed
        enviarjButtonActionPerformed(evt);
    }//GEN-LAST:event_senhajPasswordActionPerformed

    private void senhajPasswordapagarSenha2(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhajPasswordapagarSenha2
        if (this.senhajPassword.getText().equals("")) {
            this.senhajPassword.setText("");
        }
    }//GEN-LAST:event_senhajPasswordapagarSenha2

    private void enviarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarjButtonActionPerformed

        try {
            Usuario usuario = this.usuarioLoginControl.logar(this.matriculajFormattedTextField.getText(), this.senhajPassword.getText());
            if (usuario != null) {
                if (!(usuario.getLimite_Livros() > usuario.getEmprestimo().size())) {
                    JOptionPane.showMessageDialog(null, "Você chegou no limite de Livros Emprestaveis ao mesmo Tempo");
                } else {
                    usuario.atualiaEstado();

                    if (usuario.getEstado().equals("BLOQUEADO")) {
                        Date aux = new Date();

                        if (usuario.getBloqueadoAte() != null && usuario.getBloqueadoAte().getTime() > aux.getTime()) {
                            SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
                            JOptionPane.showMessageDialog(null, "Usuario bloqueado por Atraso na Devolução até: " + data.format(usuario.getBloqueadoAte()));
                        } else {
                            JOptionPane.showMessageDialog(null, "Existem Livros Com atraso de Entrega !");
                        }
                    } else {
                        Emprestimo emprestimo = new Emprestimo(usuario, new Exemplares(this.exemplares.getLivro(), 1));
                        usuario.getEmprestimo().add(emprestimo);

                        this.exemplares.setQuantidade_Disponivel(exemplares.getQuantidade_Disponivel() - 1);

                        try {
                            if (usuario instanceof Funcionario) {
                                bibliotecaDAO.editFuncionarios((Funcionario) usuario);
                            } else if (usuario instanceof Aluno) {
                                bibliotecaDAO.editAlunos((Aluno) usuario);
                            }

                            JOptionPane.showMessageDialog(null, emprestimo.toString());
                            bibliotecaDAO.editExemplares(exemplares);
                        } catch (IOException | ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }

                    if (exemplares != null) {
                        DefaultListModel<Exemplares> dflist = new DefaultListModel<>();

                        for (Exemplares i : livros) {
                            dflist.addElement(i);
                        }

                        this.lista_de_Livros.setModel(dflist);
                    }

                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Login ou senha incorretos!");
            }

        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enviarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UsuarioLoginFrame().setVisible(true);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginjLabel;
    private javax.swing.JFormattedTextField matriculajFormattedTextField;
    private javax.swing.JLabel senhajLabel;
    private javax.swing.JPasswordField senhajPassword;
    // End of variables declaration//GEN-END:variables
}
