/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controllers.CriarEmprestimoControl;
import Dao.BibliotecaDAO;
import Entidades.Exemplares;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @version 1.0
 * @author wensttay <yattsnew@gmail.com>
 * @date 07/01/2017 - 12:01:31
 */
public class CriarEmprestimoFrame extends javax.swing.JFrame {

    CriarEmprestimoControl criarEmprestimoControl;
    List<Exemplares> exemplares;
    UsuarioLoginFrame usuarioLoginFrame;
    Exemplares selectedExemplares;
    BibliotecaDAO bibliotecaDAO;

    /**
     * Creates new form FazerNovoEmprestimoFrame
     */
    /**
     *
     * @throws IOException error de arquivos
     */
    public CriarEmprestimoFrame() throws IOException {
        initComponents();
        this.criarEmprestimoControl = new CriarEmprestimoControl();
        this.exemplares = new ArrayList<>();
        this.bibliotecaDAO = new BibliotecaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        procurarjTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_De_LivrosjList = new javax.swing.JList();
        procurarjButton = new javax.swing.JButton();
        fazer_EmprestimojButton = new javax.swing.JButton();
        estadojLabel = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Novo Emprestimo");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Digite um ISBN / Titulo / Autor");

        lista_De_LivrosjList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista_De_LivrosjList.setToolTipText("");
        lista_De_LivrosjList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lista_De_LivrosjList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_De_LivrosjListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_De_LivrosjList);

        procurarjButton.setText("Procurar");
        procurarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarjButtonActionPerformed(evt);
            }
        });

        fazer_EmprestimojButton.setText("Fazer Emprestimo");
        fazer_EmprestimojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazer_EmprestimojButtonActionPerformed(evt);
            }
        });

        estadojLabel.setBackground(java.awt.Color.white);
        estadojLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        estadojLabel.setForeground(java.awt.Color.blue);
        estadojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadojLabel.setText("ESTADO");
        estadojLabel.setEnabled(false);
        estadojLabel.setRequestFocusEnabled(false);
        estadojLabel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(procurarjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(procurarjButton)
                        .addGap(12, 12, 12)
                        .addComponent(fazer_EmprestimojButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estadojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procurarjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procurarjButton)
                    .addComponent(fazer_EmprestimojButton)
                    .addComponent(estadojLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fazer_EmprestimojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazer_EmprestimojButtonActionPerformed
        Exemplares aux = (Exemplares) this.lista_De_LivrosjList.getSelectedValue();

        if (aux != null && aux.getQuantidade_Disponivel() == 0) {
            JOptionPane.showMessageDialog(null, "Não existe Exemplares Disponiveis desse livro Nesse Instante !");
        } else {
            this.selectedExemplares = aux;
            
            if (this.selectedExemplares == null) {
                JOptionPane.showMessageDialog(null, "Para realizar um emprestimo é nessesário escolher um Livro Primeio");
            } else {
                try {
                    this.usuarioLoginFrame = new UsuarioLoginFrame(this.selectedExemplares, this.selectedExemplares, this.lista_De_LivrosjList, this.exemplares);
                    this.usuarioLoginFrame.setVisible(true);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_fazer_EmprestimojButtonActionPerformed

    private void procurarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarjButtonActionPerformed

        try {
            if (this.procurarjTextField.getText() == null || this.procurarjTextField.getText().equals("")) {
                this.exemplares = this.bibliotecaDAO.getExemplares();
            } else {
                this.exemplares = this.criarEmprestimoControl.procurarExemplar(this.procurarjTextField.getText());
            }
            
            if (exemplares != null) {
                DefaultListModel<Exemplares> dflist = new DefaultListModel<>();
                for (Exemplares i : exemplares) {
                    dflist.addElement(i);
                }
                this.lista_De_LivrosjList.setModel(dflist);
            } else {
                JOptionPane.showMessageDialog(null, "Porfavor Escolha um livro Valido");
            }
            
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_procurarjButtonActionPerformed

    private void lista_De_LivrosjListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_De_LivrosjListMouseClicked
        if (this.lista_De_LivrosjList.getSelectedValue() != null) {
            this.estadojLabel.setEnabled(true);
            Exemplares aux = (Exemplares) this.lista_De_LivrosjList.getSelectedValue();
            this.estadojLabel.setText(aux.getEstado());
            
            if (aux.getEstado().equals("INDISPONIVEL")) {
                this.estadojLabel.setForeground(Color.RED);
            } else {
                this.estadojLabel.setForeground(Color.BLUE);
            }
            
        } else {
            this.estadojLabel.setEnabled(false);
            this.estadojLabel.setText("ESTADO");
            this.estadojLabel.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_lista_De_LivrosjListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CriarEmprestimoFrame().setVisible(true);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estadojLabel;
    private javax.swing.JButton fazer_EmprestimojButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList lista_De_LivrosjList;
    private javax.swing.JButton procurarjButton;
    private javax.swing.JTextField procurarjTextField;
    // End of variables declaration//GEN-END:variables
}
