/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controllers.FinalizarEmprestimoControl;
import Dao.BibliotecaDAO;
import Entidades.Aluno;
import Entidades.Constans;
import Entidades.Emprestimo;
import Entidades.Exemplares;
import Entidades.Funcionario;
import java.awt.Color;
import java.awt.Component;
import java.awt.PopupMenu;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Wensttay
 */
public class FinalizarEmprestimoFrame extends javax.swing.JFrame {
    
    FinalizarEmprestimoControl finalizarEmprestimoControl;
    List<Emprestimo> emprestimos;
    BibliotecaDAO bibliotecaDAO;
    /**
     * Creates new form FinalizarEmprestimoJFrame
     */
    /**
     * 
     * @throws IOException error de arquivos 
     */
    public FinalizarEmprestimoFrame() throws IOException {
        initComponents();
        this.finalizarEmprestimoControl = new FinalizarEmprestimoControl();
        this.emprestimos = new ArrayList<>();
        bibliotecaDAO = new BibliotecaDAO(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usuariojCheckBox = new javax.swing.JCheckBox();
        livrojCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        procurarjTextField = new javax.swing.JTextField();
        procurarjButton1 = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        finalizarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Emprestimo");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        usuariojCheckBox.setText(" CPF / Mátricula");
        usuariojCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariojCheckBoxActionPerformed(evt);
            }
        });

        livrojCheckBox.setText(" ISBN / Titulo / Autor");

        jLabel1.setText("Pesquisar por");

        procurarjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarjTextFieldActionPerformed(evt);
            }
        });

        procurarjButton1.setText("Procurar");
        procurarjButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarjButton1ActionPerformed(evt);
            }
        });
        procurarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarjButton1ActionPerformed1(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        finalizarjButton.setText("Finalizar Emprestimo");
        finalizarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarjButtonActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.cyan);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESTADO");
        jLabel2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(procurarjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(procurarjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(livrojCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuariojCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(finalizarjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(usuariojCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(livrojCheckBox))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addComponent(procurarjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(procurarjButton1)
                            .addComponent(cancelarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addComponent(finalizarjButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void finalizarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarjButtonActionPerformed
       try {
            Emprestimo aux = (Emprestimo) this.jList1.getSelectedValue();
            if (aux != null){
                aux.atualizarEstado();
                if(aux.getEstado().equals("ATRASADO")){
                    aux.getUsuario().atualiaEstado();
                    
                    int diasAtrasados = aux.autalizar_E_Pegar_Dias_Atrasados();
                    aux.setDiasAtrasados(diasAtrasados);
                    Date vaiFicarBloqueado = new Date();
                    vaiFicarBloqueado.setTime(vaiFicarBloqueado.getTime() + (Constans.DIAS_BLOQUEADOS * diasAtrasados * 86400000));
                    aux.getUsuario().setBloqueadoAte(vaiFicarBloqueado);
                    SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
                    
                    JOptionPane.showMessageDialog(null, "Devido seu atraso de " + diasAtrasados + " dias na entrega do" +
                            " livro, sua conta ficarar suspensa até o dia: " + data.format(vaiFicarBloqueado));
                    if (aux.getUsuario() instanceof Funcionario){
                        bibliotecaDAO.editFuncionarios((Funcionario) aux.getUsuario());
                    }else if (aux.getUsuario() instanceof Aluno){
                        bibliotecaDAO.editAlunos((Aluno) aux.getUsuario());
                    }
                }
                List<Exemplares> exemplares;
           
                exemplares = bibliotecaDAO.getExemplares();
                
                for(Exemplares i : exemplares){
                    if(i.getLivro().equals(aux.getExemplares().getLivro())){
                        i.setQuantidade_Disponivel(i.getQuantidade_Disponivel() + 1);
                        bibliotecaDAO.editExemplares(i);
                        break;
                    }
                }
                List<Emprestimo> minhaLista = aux.getUsuario().getEmprestimo();
                for(Emprestimo i : minhaLista) {
                    if(i.hashCode() == aux.hashCode()){
                        minhaLista.remove(i);
                        break;
                    }
                }
                if(aux.getUsuario() instanceof Funcionario){
                    bibliotecaDAO.editFuncionarios((Funcionario) aux.getUsuario());
                }else if( aux.getUsuario() instanceof Aluno){
                    bibliotecaDAO.editAlunos((Aluno) aux.getUsuario());
                }    
                JOptionPane.showMessageDialog(null, "Emprestimo Finalizado Com sucesso ");
            }else{
                JOptionPane.showMessageDialog(null, "É necessário selecionar o emprestimo a ser finalizado ");
            }
            
            DefaultListModel<Emprestimo> 
            listanova = null;
            List<Emprestimo> emp = null;
            if (this.usuariojCheckBox.isSelected() && this.livrojCheckBox.isSelected()){
                emp = this.finalizarEmprestimoControl.procurarGeral(this.procurarjTextField.getText());
            }else if (this.usuariojCheckBox.isSelected()){
                emp = this.finalizarEmprestimoControl.procurarUsuario(this.procurarjTextField.getText());
            }else if (this.livrojCheckBox.isSelected()){
                emp = this.finalizarEmprestimoControl.procurarLivro(this.procurarjTextField.getText());
            }else{
                listanova = new DefaultListModel<>();
                int contador = 0;
                for(int i = 0; i < jList1.getModel().getSize(); i++){
                    if(!jList1.getModel().getElementAt(i).equals(aux)){
                       listanova.addElement((Emprestimo) jList1.getModel().getElementAt(i));
                       if (contador == 1){
                           break;
                       }
                    }else{
                        contador += 1;
                    }
                }
            }
            
            if (emp != null){  
                DefaultListModel<Emprestimo> nova = new DefaultListModel<>();
                for(Emprestimo i : emp){
                    nova.addElement(i);
                }
                this.jList1.setModel(nova);
            }else if (listanova != null ){
                this.jList1.setModel(listanova);
            }
            
        } catch (IOException | ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_finalizarjButtonActionPerformed

    private void usuariojCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariojCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariojCheckBoxActionPerformed

    private void procurarjButton1ActionPerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarjButton1ActionPerformed

    private void procurarjButton1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarjButton1ActionPerformed1
        try {
            List<Emprestimo> emp;
            if(this.procurarjTextField.getText() == null || this.procurarjTextField.getText().equals("")){
                emp = this.finalizarEmprestimoControl.procurarGeral();
            }else{
                if (this.usuariojCheckBox.isSelected() && this.livrojCheckBox.isSelected()){
                    emp = this.finalizarEmprestimoControl.procurarGeral(this.procurarjTextField.getText());
                }else if (this.usuariojCheckBox.isSelected()){
                    emp = this.finalizarEmprestimoControl.procurarUsuario(this.procurarjTextField.getText());
                }else if (this.livrojCheckBox.isSelected()){
                    emp = this.finalizarEmprestimoControl.procurarLivro(this.procurarjTextField.getText());
                }else{
                    emp = new ArrayList<>();
                }
            }
            if (emp != null){  
                DefaultListModel<Emprestimo> aux = new DefaultListModel<>();
                for(Emprestimo i : emp){
                    aux.addElement(i);
                }
                this.jList1.setModel(aux);
            }
        } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_procurarjButton1ActionPerformed1

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
       if(this.jList1.getSelectedValue() != null){
           this.finalizarjButton.setEnabled(true);
           this.jLabel2.setEnabled(true);
           Emprestimo aux = (Emprestimo) this.jList1.getSelectedValue();
           this.jLabel2.setText(aux.getEstado());
           if(aux.getEstado().equals("ATRASADO")){
               this.finalizarjButton.setEnabled(true);
               this.jLabel2.setForeground(Color.RED);
               aux.atualizarEstado();
               aux.getUsuario().set_Estado_Entregar_Livro_Atasado(aux);
           }else if(aux.getEstado().equals("EM ANDAMENTO")){
               this.finalizarjButton.setEnabled(true);
               this.jLabel2.setForeground(Color.BLUE);
               aux.atualizarEstado();
           }else if(aux.getEstado().equals("CONCLUIDO")){
               this.finalizarjButton.setEnabled(false);
           }
       }else{
           this.jLabel2.setEnabled(false);
           this.jLabel2.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_jList1MouseClicked

    private void procurarjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procurarjTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarEmprestimoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FinalizarEmprestimoFrame().setVisible(true);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton finalizarjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox livrojCheckBox;
    private javax.swing.JButton procurarjButton1;
    private javax.swing.JTextField procurarjTextField;
    private javax.swing.JCheckBox usuariojCheckBox;
    // End of variables declaration//GEN-END:variables
}
