/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controllers.*;
import Dao.BibliotecaDAO;
import Entidades.Constans;
import Entidades.Funcionario;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Wensttay
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private LoginControl loginControl;
    private GeralControl geralControl;
    private BibliotecaDAO bibliotecaDAO;
    
    /**
     * Creates new form LoginFrame
     */
    /**
     * 
     * @throws IOException error de arquivos 
     */
    public LoginFrame() throws IOException {
        initComponents();
        bibliotecaDAO = new BibliotecaDAO();
        loginControl = new LoginControl();
        geralControl = new GeralControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginjLabel = new javax.swing.JLabel();
        senhajPassword = new javax.swing.JPasswordField();
        senhajLabel = new javax.swing.JLabel();
        enviarjButton = new javax.swing.JButton();
        loginjFormattedTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        loginjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginjLabel.setText("Matrícula");

        senhajPassword.setToolTipText("Digite sua Senha");
        senhajPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apagarSenha(evt);
            }
        });
        senhajPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhajPasswordActionPerformed(evt);
            }
        });
        senhajPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                senhajPasswordKeyTyped(evt);
            }
        });

        senhajLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        senhajLabel.setText("Senha");

        enviarjButton.setText("Enviar");
        enviarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarjButtonActionPerformed(evt);
            }
        });

        try {
            loginjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        loginjFormattedTextField.setToolTipText("Digite sua Matrícula");
        loginjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjFormattedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enviarjButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhajLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhajPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(loginjFormattedTextField))))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginjLabel)
                    .addComponent(loginjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhajPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhajLabel))
                .addGap(18, 18, 18)
                .addComponent(enviarjButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enviarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarjButtonActionPerformed
        String login = loginjFormattedTextField.getText();
        char[] pwr = senhajPassword.getPassword();
        String senha = new String(pwr);
        
        
        try {
            Funcionario aux = this.loginControl.logar_Funcionario(login,senha, this.bibliotecaDAO.getFuncionarios());
            if(aux != null){
                geralControl.setFuncionario_Logado(aux);
                this.dispose();
                LogadoFrame logadoFrame = new LogadoFrame(this.geralControl,this);
                logadoFrame.setVisible(true);
            }else{
                if(!this.loginControl.funcionario_Existe(login,senha, this.bibliotecaDAO.getFuncionarios())){
                    JOptionPane.showMessageDialog(null,"Essa Conta Funcionario não Existe","Error",JOptionPane.ERROR_MESSAGE);
                    this.senhajPassword.setText("");
                    this.loginjFormattedTextField.setText("");
                }else{
                    JOptionPane.showMessageDialog(null,"Matricula ou Senha estão incorretos","Aviso",JOptionPane.WARNING_MESSAGE);
                }  
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_enviarjButtonActionPerformed

    private void apagarSenha(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apagarSenha
        this.senhajPassword.setText("");
    }//GEN-LAST:event_apagarSenha

    private void senhajPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhajPasswordKeyTyped
       int tamanho = senhajPassword.getText().length();
       if(tamanho > Constans.TAMANHO_DE_SENHA){
           evt.consume();
       }
    }//GEN-LAST:event_senhajPasswordKeyTyped

    private void senhajPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhajPasswordActionPerformed
        this.enviarjButton.doClick();
    }//GEN-LAST:event_senhajPasswordActionPerformed

    private void loginjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjFormattedTextFieldActionPerformed
        this.enviarjButton.doClick();
    }//GEN-LAST:event_loginjFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LoginFrame().setVisible(true);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Arquivo não encontrado", "File Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField loginjFormattedTextField;
    private javax.swing.JLabel loginjLabel;
    private javax.swing.JLabel senhajLabel;
    private javax.swing.JPasswordField senhajPassword;
    // End of variables declaration//GEN-END:variables

}
